### ISSUE TITLE
No arquivo de suporte sobre Ofuscamento está faltando o link para Api Manager

### ISSUE THREAD

**Issue by joaoalbuquerquezup** [zup-academy/nosso-cartao-documentacao#42]
Como foi sugerido pra gente no check-out, tô abrindo uma issue de uma besteirinha aqui no cartão de ofuscamento.

No final do arquivo há um link de referência incompleto para o API Manager. Imagino que seja esse: 
- https://www.zup.com.br/produtos/api-manager

Link para o cartão:
- https://github.com/zup-academy/nosso-cartao-documentacao/blob/master/informacao_procedural/ofuscamento.md

**Comment by luramarchanjozup** [comment]
Muito obrigado @joaoalbuquerquezup , ajuste feito!
